(() => {
'use strict';
const V='1.8.0', ROUNDS=6;
MODES.quantum={title:'Quantum Trace',rounds:ROUNDS}; modeNames.quantum='Quantum Trace';
MODE_HELP.quantum='Une impulsion traverse un réseau quantique. Observe son trajet, puis reconstruis-le en touchant les nœuds dans le même ordre. Les portails et leurres apparaissent aux niveaux avancés.';
defaultData.best.quantum=0; data.best.quantum??=0; data.modeStats.quantum??={plays:0,quickLegs:0,correct:0,total:0,totalScore:0,quickScore:0,bestCombo:0,bestSpeed:0}; data.recent.quantum??=[]; saveData();
const S={seq:[],input:[],timers:[],d:null};
const later=(f,m)=>{const x=setTimeout(f,m);S.timers.push(x)}; const clear=()=>{S.timers.forEach(clearTimeout);S.timers=[]};
function inject(){const g=document.querySelector('.game-grid');if(!g||g.querySelector('[data-mode="quantum"]'))return;const b=document.createElement('button');b.className='game-card quantum-card';b.dataset.mode='quantum';b.innerHTML='<span class="quantum-ribbon">SIGNATURE</span><span class="game-icon quantum-icon"><i></i><b></b><em></em></span><span class="game-copy"><strong>Quantum Trace</strong><small>Recompose le signal</small></span><span class="game-meta"><span class="mode-diff" id="diff-quantum">Auto</span><span class="record-mini"><b id="best-quantum">0</b><small>record</small></span></span>';b.onclick=()=>requestStartGame('quantum');g.append(b)}
function cfg(d,r){return {nodes:[0,5,6,7,8,9][d],len:[0,3,4,5,6,7][d]+(r>3?1:0),pulse:[0,650,570,500,440,390][d],limit:[0,11000,10000,9000,8000,7000][d]}}
function pos(i,n){const a=-Math.PI/2+i*Math.PI*2/n;const rad=38;return [50+Math.cos(a)*rad,50+Math.sin(a)*rad]}
function build(c){const n=c.nodes;return Array.from({length:n},(_,i)=>{const [x,y]=pos(i,n);return {i,x,y}})}
function sequence(c){const a=[];while(a.length<c.len){let x=rnd(0,c.nodes-1);if(x!==a[a.length-1])a.push(x)}return a}
function render(c){const nodes=build(c),d=S.d||effectiveDifficulty('quantum');const lines=nodes.map((p,i)=>{const q=nodes[(i+1)%nodes.length];return '<line x1="'+p.x+'" y1="'+p.y+'" x2="'+q.x+'" y2="'+q.y+'"/>'}).join('');$('playStage').innerHTML='<div class="qt-wrap"><div class="qt-head"><div><span>NEURAL LINK</span><strong id="qtTitle">Observe le signal</strong><small id="qtSub">Mémorise son trajet dans le réseau</small></div><label><span>Niveau</span><select id="qtDiff">'+[1,2,3,4,5].map(x=>'<option value="'+x+'" '+(x===d?'selected':'')+'>'+DIFF_NAMES[x]+'</option>').join('')+'</select></label></div><div class="qt-arena"><svg viewBox="0 0 100 100" aria-hidden="true">'+lines+'</svg><div class="qt-core"><i></i></div>'+nodes.map(p=>'<button disabled class="qt-node" data-n="'+p.i+'" style="left:'+p.x+'%;top:'+p.y+'%" aria-label="Nœud '+(p.i+1)+'"><span></span></button>').join('')+'<div class="qt-scan"></div></div><div class="qt-status"><span id="qtPhase">ANALYSE</span><b id="qtProgress">0 / '+S.seq.length+'</b></div></div>';const sel=$('qtDiff');sel.onchange=()=>{S.d=+sel.value;clear();stopTimer();quantumRound()}}
function flash(id,k){document.querySelectorAll('.qt-node').forEach(x=>x.classList.remove('active'));const b=document.querySelector('.qt-node[data-n="'+id+'"]');if(!b)return;b.classList.add('active');$('qtTitle').textContent='Signal '+(k+1)+' sur '+S.seq.length;$('qtProgress').textContent=(k+1)+' / '+S.seq.length;haptic(5)}
function recall(c){document.querySelectorAll('.qt-node').forEach(x=>{x.classList.remove('active');x.disabled=false;x.onclick=()=>tap(+x.dataset.n,x,c)});$('qtPhase').textContent='À TOI';$('qtTitle').textContent='Recompose le signal';$('qtSub').textContent='Touche les nœuds dans le même ordre';$('qtProgress').textContent='0 / '+S.seq.length;runTimer(c.limit,()=>fail())}
function present(c){S.seq.forEach((id,i)=>later(()=>flash(id,i),550+i*c.pulse));later(()=>recall(c),550+S.seq.length*c.pulse+180)}
function tap(id,b,c){if(current.locked)return;const k=S.input.length;if(id!==S.seq[k])return fail(b);S.input.push(id);b.classList.add('good');later(()=>b.classList.remove('good'),180);$('qtProgress').textContent=S.input.length+' / '+S.seq.length;haptic(7);if(S.input.length===S.seq.length)win()}
function fail(b){if(current.locked)return;current.locked=true;stopTimer();clear();record(false);current.combo=0;if(b)b.classList.add('bad');$('qtTitle').textContent='Signal perdu';feedback(false);safeTimeout(nextRound,850)}
function win(){if(current.locked)return;current.locked=true;const sp=speedFraction();stopTimer();clear();record(true);addSpeedSample(sp);current.combo++;current.maxCombo=Math.max(current.maxCombo,current.combo);setScore((170+S.seq.length*48+current.combo*14)*difficultyBonus('quantum')*(1+.4*sp));$('qtTitle').textContent='Connexion établie';$('qtSub').textContent='Synchronisation parfaite';document.querySelector('.qt-core')?.classList.add('success');feedback(true);safeTimeout(nextRound,760)}
function quantumRound(){clear();current.locked=false;const d=S.d||effectiveDifficulty('quantum'),c=cfg(d,current.round);S.seq=sequence(c);S.input=[];render(c);$('timerMeter').style.width='100%';present(c)}
const oldNext=nextRound;nextRound=function(){if(current.mode!=='quantum'||current.quick)return oldNext();current.locked=false;if(current.round>=ROUNDS){finishGame();return}current.round++;$('roundLabel').textContent='TRACE '+current.round+'/'+ROUNDS;quantumRound()};
const oldShow=showView;showView=function(id){if(id!=='gameView'&&current.mode==='quantum')clear();return oldShow(id)};
inject();updateHome();document.querySelectorAll('.app-version').forEach(x=>x.textContent=V.replace(/\.0$/,''));
})();