(() => {
'use strict';
const V='2.0.0',ROUNDS=6;
MODES.quantum={title:'Quantum Grid',rounds:ROUNDS};modeNames.quantum='Quantum Grid';
MODE_HELP.quantum='Pilote un réacteur vivant en temps réel. Chaque impulsion colorée doit être routée vers le port de même couleur : touche une jonction pour changer sa voie avant qu’elle n’atteigne le noyau.';
defaultData.best.quantum=0;data.best.quantum??=0;data.modeStats.quantum??={plays:0,quickLegs:0,correct:0,total:0,totalScore:0,quickScore:0,bestCombo:0,bestSpeed:0};data.recent.quantum??=[];saveData();
const C=['#59e9ff','#a982ff','#ff72bd','#ffd166'];
const S={timers:[],raf:0,pulses:[],gates:[0,1,2,3],start:0,duration:0,last:0,spawn:0,lives:3,hit:0,miss:0,d:null,running:false};
const clear=()=>{S.timers.forEach(clearTimeout);S.timers=[];cancelAnimationFrame(S.raf);S.running=false};
function inject(){const g=document.querySelector('.game-grid');if(!g||g.querySelector('[data-mode="quantum"]'))return;const b=document.createElement('button');b.className='game-card quantum-card';b.dataset.mode='quantum';b.innerHTML='<span class="quantum-ribbon">TEMPS RÉEL</span><span class="game-icon quantum-icon"><i></i><b></b><em></em></span><span class="game-copy"><strong>Quantum Grid</strong><small>Pilote le réacteur</small></span><span class="game-meta"><span class="mode-diff" id="diff-quantum">Auto</span><span class="record-mini"><b id="best-quantum">0</b><small>record</small></span></span>';b.onclick=()=>requestStartGame('quantum');g.append(b)}
function cfg(d){return {duration:[0,14500,15500,16500,17500,18500][d],interval:[0,1900,1600,1350,1120,920][d],speed:[0,.00016,.00019,.00022,.00025,.00029][d],lanes:d<3?3:4}}
function render(c){const d=S.d||effectiveDifficulty('quantum');$('playStage').innerHTML='<div class="qg-wrap"><div class="qg-head"><div><span>LIVE REACTOR</span><strong id="qgTitle">Stabilise le réseau</strong><small id="qgSub">Route chaque énergie vers sa couleur</small></div><label><span>Niveau</span><select id="qgDiff">'+[1,2,3,4,5].map(x=>'<option value="'+x+'" '+(x===d?'selected':'')+'>'+DIFF_NAMES[x]+'</option>').join('')+'</select></label></div><div class="qg-hud"><span>INTÉGRITÉ <b id="qgLives">◆ ◆ ◆</b></span><span>STABILITÉ <b id="qgScore">0</b></span></div><div class="qg-arena" id="qgArena"><div class="qg-grid"></div><div class="qg-core"><i></i><span>CORE</span></div>'+Array.from({length:c.lanes},(_,i)=>'<button class="qg-gate g'+i+'" data-g="'+i+'" aria-label="Changer la sortie '+(i+1)+'"><span style="--c:'+C[S.gates[i]]+'"></span><b>↻</b></button><div class="qg-port p'+i+'" style="--c:'+C[i]+'"><i></i></div>').join('')+'<div class="qg-pulses" id="qgPulses"></div><div class="qg-sweep"></div></div><div class="qg-help"><span>TOUCHE UNE JONCTION POUR CHANGER SA COULEUR</span><b id="qgTime">—</b></div></div>';document.querySelectorAll('.qg-gate').forEach(b=>b.onclick=()=>cycle(+b.dataset.g,c));$('qgDiff').onchange=()=>{S.d=+$('qgDiff').value;clear();stopTimer();quantumRound()}}
function cycle(i,c){S.gates[i]=(S.gates[i]+1)%c.lanes;const s=document.querySelector('.qg-gate[data-g="'+i+'"] span');if(s)s.style.setProperty('--c',C[S.gates[i]]);haptic(5)}
function spawn(c,now){const lane=rnd(0,c.lanes-1),type=rnd(0,c.lanes-1);S.pulses.push({lane,type,t:0,id:Math.random()});S.spawn=now}
function pulsePos(p){const ang=(-90+p.lane*(360/(S.gates.length)))*Math.PI/180;const r=44*(1-p.t)+9*p.t;return {x:50+Math.cos(ang)*r,y:50+Math.sin(ang)*r}}
function draw(c){const h=$('qgPulses');if(!h)return;h.innerHTML=S.pulses.map(p=>{const q=pulsePos(p);return '<i class="qg-pulse" style="left:'+q.x+'%;top:'+q.y+'%;--c:'+C[p.type]+'"></i>'}).join('')}
function resolve(p,c){const ok=S.gates[p.lane]===p.type;record(ok);if(ok){S.hit++;current.combo++;current.maxCombo=Math.max(current.maxCombo,current.combo);setScore((45+current.combo*7)*difficultyBonus('quantum'));flashGate(p.lane,'ok')}else{S.miss++;S.lives--;current.combo=0;flashGate(p.lane,'no');haptic(18)}$('qgLives').textContent=Array.from({length:3},(_,i)=>i<S.lives?'◆':'◇').join(' ');$('qgScore').textContent=S.hit;if(S.lives<=0)finish(false)}
function flashGate(i,k){const e=document.querySelector('.qg-gate[data-g="'+i+'"]');if(!e)return;e.classList.add(k);setTimeout(()=>e.classList.remove(k),260)}
function loop(now,c){if(!S.running)return;const dt=Math.min(40,now-S.last);S.last=now;if(now-S.spawn>c.interval)spawn(c,now);for(const p of S.pulses)p.t+=dt*c.speed;const done=S.pulses.filter(p=>p.t>=1);S.pulses=S.pulses.filter(p=>p.t<1);done.forEach(p=>resolve(p,c));draw(c);const remain=Math.max(0,S.duration-(now-S.start));$('qgTime').textContent=(remain/1000).toFixed(1)+' s';$('timerMeter').style.width=(remain/S.duration*100)+'%';if(!S.running)return;if(remain<=0)return finish(true);S.raf=requestAnimationFrame(n=>loop(n,c))}
function finish(survived){if(!S.running||current.locked)return;S.running=false;current.locked=true;cancelAnimationFrame(S.raf);record(survived&&S.hit>S.miss);if(survived){$('qgTitle').textContent='Réacteur stabilisé';$('qgSub').textContent=S.hit+' flux synchronisés';feedback(true)}else{$('qgTitle').textContent='Surcharge critique';$('qgSub').textContent='Le réseau a perdu sa stabilité';feedback(false)}setTimeout(nextRound,900)}
function quantumRound(){clear();current.locked=false;const d=S.d||effectiveDifficulty('quantum'),c=cfg(d);S.gates=[0,1,2,3];for(let i=c.lanes-1;i>0;i--){const j=rnd(0,i);[S.gates[i],S.gates[j]]=[S.gates[j],S.gates[i]]}S.pulses=[];S.lives=3;S.hit=0;S.miss=0;render(c);S.duration=c.duration;S.start=performance.now()+650;S.last=S.start;S.spawn=S.start-c.interval*.55;S.running=true;setTimeout(()=>{if(S.running)S.raf=requestAnimationFrame(n=>loop(n,c))},650)}
const oldNext=nextRound;nextRound=function(){if(current.mode!=='quantum'||current.quick)return oldNext();current.locked=false;if(current.round>=ROUNDS){finishGame();return}current.round++;$('roundLabel').textContent='RÉACTEUR '+current.round+'/'+ROUNDS;quantumRound()};
const oldShow=showView;showView=function(id){if(id!=='gameView'&&current.mode==='quantum')clear();return oldShow(id)};
inject();updateHome();document.querySelectorAll('.app-version').forEach(x=>x.textContent=V.replace(/\.0$/,''));
})();